In [1]:
import pandas as pd
import re

In [2]:
bangmok = pd.read_csv('bangmok.csv')

In [7]:
cnt = pd.DataFrame(bangmok.groupby('pass_year').size()).reset_index().rename(columns={0:'count', 'pass_year':'year'})
# cnt.to_json('bangmok_year.json', orient='records')

In [8]:
freq = bangmok[bangmok['rank']==1].groupby(['pass_year','rank']).size().reset_index()
freq.columns = ['year','rank','freq']
# freq[['year','freq']].to_json('bangmok_year_freq.json', orient='records')

In [12]:
pd.merge(cnt, freq, on='year')[['year','count','freq']].to_json('bangmok_count.json', orient='records')

In [3]:
bp = pd.read_csv("bangmok_person.csv")

In [8]:
bangmok

,bid,bpid,affilliation,rank,competitors,exam_type,pass_year,king,lid,previous,exam_class,class_rank,pass_date
0,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13C774C218B4DDB1697X0,문과,3,15,정시2,1753,영조,30,부사과(副司果),을과(乙科),2,1753-07-01
1,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13C720C5B8C220B1703X0,문과,3,7,중시,1757,영조,30,세자시강원보덕(世子侍講院輔德),을과(乙科),2,1757-07-01
2,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13C2E0AE30D604B1747X0,문과,15,18,정시,1784,정조,30,유학(幼學),병과(丙科),12,1784-07-01
3,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13BC15C885ACB8B1744X0,문과,5,10,정시,1785,정조,30,유학(幼學),병과(丙科),2,1785-07-01
4,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13AE40CC3DB95CB1843X0,문과,6,18,정시,1864,고종,80,유학(幼學),병과(丙科),3,1864-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15146,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13C774C7ACADF9B1864X0,문과,7,32,정시,1893,고종,305,유학(幼學),병과(丙科),5,1893-07-01
15147,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_12AC15D56DFFFFB1702X0,문과,9,35,식년시,1726,영조,123,생원(生員),을과(乙科),6,1726-07-01
15148,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_12D64DC11CFFFFB1583X0,문과,4,11,정시,1621,광해,305,공조정랑(工曹正郞),병과(丙科),2,1621-07-01
15149,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13AE40C218C628B1409X0,문과,1,12,등준시,1466,세조,96,판중추부사(判中樞府事),갑과(甲科),1,1466-07-01
15150,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13C774C6B4C775B1826X0,문과,2,5,중시,1866,고종,79,부사직(副司直),을과(乙科),1,1866-07-01

In [4]:
bm = pd.merge(bangmok, bp, on='bpid').sort_values(['bpid','pass_year'], ascending=True).drop_duplicates(['bpid'], keep="first").reset_index().drop(['index'], axis=1)

In [18]:
bm

,bid,bpid,affilliation,rank,competitors,exam_type,pass_year,king,lid,previous,exam_class,class_rank,pass_date,chnname,korname,family_clan,birth,death,plastic
0,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_12AC15AC04FFFFB1700X0,문과,5,51,식년시,1733,영조,216,생원(生員),을과(乙科),2,1733-07-01,康侃,강간,곡산(谷山),1700.0,NaN,plastic
1,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_12AC15AC74FFFFB1808X0,문과,33,40,증광시,1859,철종,149,장사랑(將仕郞),병과(丙科),23,1859-07-01,姜鍵,강건,진주(晉州),1808.0,NaN,silver
2,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_12AC15ACB8FFFFD1504X0,문과,20,33,식년시,1480,성종,96,장사랑(將仕郞),병과(丙科),10,1480-07-01,姜謙,강겸,진주(晉州),NaN,1504.0,silver
3,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_12AC15AD00FFFFU9999X0,문과,20,33,식년시,1510,중종,96,생원(生員),병과(丙科),10,1510-07-01,姜琯,강관,진주(晉州),NaN,NaN,silver
4,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_12AC15AE30FFFFB1787X0,문과,3,39,증광시,1844,헌종,305,현감(縣監),갑과(甲科),3,1844-07-01,姜𣹡,강기,진주(晉州),1787.0,NaN,silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14633,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13D669D68CC5F0B1854X0,문과,72,78,증광시,1891,고종,321,참봉(參奉),병과(丙科),62,1891-07-01,黃會淵,황회연,창원(昌原),1854.0,NaN,silver
14634,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13D669D68CC601B1787X0,문과,7,40,증광시,1827,순조,16,참봉(參奉),을과(乙科),4,1827-07-01,黃晦瑛,황회영,평해(平海),1787.0,NaN,plastic
14635,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13D669D6A8ACF5B1496X0,문과,8,18,별시,1521,중종,96,유학(幼學),병과(丙科),4,1521-07-01,黃孝恭,황효공,장수(長水),1496.0,1553.0,silver
14636,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13D669D6A8C6D0B1414X0,문과,1,33,식년시,1444,세종,96,생원(生員),을과(乙科),1,1444-07-01,黃孝源,황효원,상주(尙州),1414.0,1481.0,silver
14637,http://people.aks.ac.kr/front/dirSer/exm/exmVi...,G002+AKS-KHF_13D669D6A8D5CCB1491X0,문과,5,21,별시,1514,중종,305,진사(進士),을과(乙科),3,1514-07-01,黃孝獻,황효헌,장수(長水),1491.0,1532.0,silver

In [5]:
bm['pass_age'] = bm['pass_year'] - bm['birth']
bm['lifespan'] = bm['death'] - bm['birth']
bm['office_span'] = bm['death'] - bm['pass_year']

In [78]:
yangban_age = bm[['pass_age','lifespan','office_span']]
yangban_age = yangban_age.dropna()
yangban_age.to_json('yangban_age.json', orient='records')

In [51]:
import requests
from lxml import html

d = html.fromstring(requests.get("https://ko.wikipedia.org/wiki/%EC%A1%B0%EC%84%A0_%EA%B5%AD%EC%99%95").text).xpath('//*[@id="mw-content-text"]/div[1]/center[1]/table/tbody//tr/td[3]')

In [58]:
kings = [ i.text.strip('\n').split(' - ') for i in d]
kings = [[int(k[0].replace('년', "")), int(k[1].replace('년', ""))] for k in kings]

In [63]:
kings = pd.DataFrame(kings, columns=['birth','death'])

In [64]:
king_name = "태조 정종 태종 세조 문종 단종 세조 예종 성종 연산 인종 명종 선조 광해 인조 효종 현종 숙종 경종 영조 정조 순조 헌종 철종 고종".split(' ')
kings['king'] = pd.Series(king_name)

In [66]:
kings['lifespan'] = kings['death'] - kings['birth']

In [68]:
kings.to_csv('kings.csv', index=False)

In [79]:
kings['lifespan']

    birth  death king  lifespan
0    1335   1408   태조        73
1    1357   1419   정종        62
2    1367   1422   태종        55
3    1397   1450   세조        53
4    1414   1452   문종        38
5    1441   1457   단종        16
6    1417   1468   세조        51
7    1450   1469   예종        19
8    1457   1494   성종        37
9    1476   1506   연산        30
10   1488   1544   인종        56
11   1515   1545   명종        30
12   1534   1567   선조        33
13   1552   1608   광해        56
14   1575   1641   인조        66
15   1595   1649   효종        54
16   1619   1659   현종        40
17   1641   1674   숙종        33
18   1661   1720   경종        59
19   1688   1724   영조        36
20   1694   1776   정조        82
21   1752   1800   순조        48
22   1790   1834   헌종        44
23   1827   1849   철종        22
24   1831   1863   고종        32
25   1852   1919  NaN        67

In [87]:
enunch['status'] = 'eunuch'
kings['status'] = 'king'
yangban_age['status'] = 'yangban'

In [88]:
pd.concat([enunch[['lifespan', 'status']], kings[['lifespan', 'status']], yangban_age[['lifespan', 'status']]]).to_json('lifespan.json', orient='records')

In [42]:
import json
with open('gwageo.json', 'r') as f:
    gwageo = json.load(f)
gwageo

{'nodes': [{'node': 0, 'name': '소과 - 서울'},
  {'node': 1, 'name': '소과 - 초시'},
  {'node': 2, 'name': '소과 - 경기'},
  {'node': 3, 'name': '소과 - 강원'},
  {'node': 4, 'name': '소과 - 충청'},
  {'node': 5, 'name': '소과 - 전라'},
  {'node': 6, 'name': '소과 - 경상'},
  {'node': 7, 'name': '소과 - 황해'},
  {'node': 8, 'name': '소과 - 평안'},
  {'node': 9, 'name': '소과 - 함경'},
  {'node': 10, 'name': '소과 - 복시'},
  {'node': 11, 'name': '소과 - 성균관'},
  {'node': 12, 'name': '대과 - 초시'},
  {'node': 13, 'name': '대과 - 서울'},
  {'node': 14, 'name': '대과 - 경기'},
  {'node': 15, 'name': '대과 - 강원'},
  {'node': 16, 'name': '대과 - 황해'},
  {'node': 17, 'name': '대과 - 충청'},
  {'node': 18, 'name': '대과 - 경상'},
  {'node': 19, 'name': '대과 - 전라'},
  {'node': 20, 'name': '대과 - 평안'},
  {'node': 21, 'name': '대과 - 함경'},
  {'node': 22, 'name': '대과 - 복시'},
  {'node': 23, 'name': '대과 - 전시'}],
 'links': [{'source': 0, 'target': 1, 'value': 200},
  {'source': 2, 'target': 1, 'value': 60},
  {'source': 3, 'target': 1, 'value': 45},
  {'source': 4, 'target': 1, 'value': 90},
  {'source': 5, 'target': 1, 'value': 90},
  {'source': 6, 'target': 1, 'value': 100},
  {'source': 7, 'target': 1, 'value': 35},
  {'source': 8, 'target': 1, 'value': 45},
  {'source': 9, 'target': 1, 'value': 35},
  {'source': 1, 'target': 10, 'value': 100},
  {'source': 10, 'target': 11, 'value': 100},
  {'source': 11, 'target': 12, 'value': 50},
  {'source': 13, 'target': 12, 'value': 40},
  {'source': 14, 'target': 12, 'value': 20},
  {'source': 15, 'target': 12, 'value': 15},
  {'source': 16, 'target': 12, 'value': 10},
  {'source': 17, 'target': 12, 'value': 25},
  {'source': 18, 'target': 12, 'value': 30},
  {'source': 19, 'target': 12, 'value': 25},
  {'source': 20, 'target': 12, 'value': 15},
  {'source': 21, 'target': 12, 'value': 10},
  {'source': 12, 'target': 22, 'value': 33},
  {'source': 22, 'target': 23, 'value': 33}]}

In [43]:
import pandas as pd
gnodes = pd.DataFrame(gwageo['nodes'])

In [19]:
gnodes

    node      name
0      0   소과 - 서울
1      1   소과 - 초시
2      2   소과 - 경기
3      3   소과 - 강원
4      4   소과 - 충청
5      5   소과 - 전라
6      6   소과 - 경상
7      7   소과 - 황해
8      8   소과 - 평안
9      9   소과 - 함경
10    10   소과 - 복시
11    11  소과 - 성균관
12    12   대과 - 초시
13    13   대과 - 서울
14    14   대과 - 경기
15    15   대과 - 강원
16    16   대과 - 황해
17    17   대과 - 충청
18    18   대과 - 경상
19    19   대과 - 전라
20    20   대과 - 평안
21    21   대과 - 함경
22    22   대과 - 복시
23    23   대과 - 전시

In [44]:
glinks = pd.DataFrame(gwageo['links'])

In [45]:
nd = {k:v for k, v in zip(gnodes.node, gnodes.name)}

In [46]:
glinks['source_name'] = glinks['source'].map(nd)
glinks['target_name'] = glinks['target'].map(nd)
glinks

    source  target  value source_name target_name
0        0       1    200     소과 - 서울     소과 - 초시
1        2       1     60     소과 - 경기     소과 - 초시
2        3       1     45     소과 - 강원     소과 - 초시
3        4       1     90     소과 - 충청     소과 - 초시
4        5       1     90     소과 - 전라     소과 - 초시
5        6       1    100     소과 - 경상     소과 - 초시
6        7       1     35     소과 - 황해     소과 - 초시
7        8       1     45     소과 - 평안     소과 - 초시
8        9       1     35     소과 - 함경     소과 - 초시
9        1      10    100     소과 - 초시     소과 - 복시
10      10      11    100     소과 - 복시    소과 - 성균관
11      11      12     50    소과 - 성균관     대과 - 초시
12      13      12     40     대과 - 서울     대과 - 초시
13      14      12     20     대과 - 경기     대과 - 초시
14      15      12     15     대과 - 강원     대과 - 초시
15      16      12     10     대과 - 황해     대과 - 초시
16      17      12     25     대과 - 충청     대과 - 초시
17      18      12     30     대과 - 경상     대과 - 초시
18      19      12     25     대과 - 전라     대과 - 초시
19      20      12     15     대과 - 평안     대과 - 초시
20      21      12     10     대과 - 함경     대과 - 초시
21      12      22     33     대과 - 초시     대과 - 복시
22      22      23     33     대과 - 복시     대과 - 전시

In [47]:
glinks.to_csv('gwageo_links.csv', index=False)

In [40]:
glinks['source_name2'] = glinks['source_name'].apply(lambda x: x.split(" - ")[1])
glinks['source_target2'] = glinks['target_name'].apply(lambda x: x.split(" - ")[1])

In [48]:
gl = pd.read_csv("gwageo_edges.csv")
gn = pd.read_csv("gwageo_nodes.csv")

In [51]:
res = {}

In [52]:
res['nodes'] = gn.to_dict('records')
res['links'] = gl.to_dict('records')

In [54]:
with open('gwageo2.json', 'w') as f:
    json.dump(res, f)

In [1]:
"태조 정종 태종 세조 문종 단종 세조 예종 성종 연산 인종 명종 선조 광해 인조 효종 현종 숙종 경종 영조 정조 순조 헌종 철종 고종".split(' ')

['태조',
 '정종',
 '태종',
 '세조',
 '문종',
 '단종',
 '세조',
 '예종',
 '성종',
 '연산',
 '인종',
 '명종',
 '선조',
 '광해',
 '인조',
 '효종',
 '현종',
 '숙종',
 '경종',
 '영조',
 '정조',
 '순조',
 '헌종',
 '철종',
 '고종']